config/routes.rb
Assignment::Application.routes.draw do
  resources :items
  resources :todo_lists
  root :to => 'todo_lists#index'

  scope "/todo_lists/:todo_list_id/" do
    match "/items"=>"items#index",as: :todo_list_items
    match "/items/new"=>"items#new",as: :todo_list_new_item
    match "/items/edit/:id"=>"items#edit",as: :edit_todo_list_item
  end


end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :todo_list ,counter_cache: true
  #default_scope order('created_at DESC')

  attr_accessible :checked, :name, :todo_list_id
  #validates_presence_of :todo_list_id, :name, :checked
  validates :todo_list_id,:name,presence: true
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :items

  attr_accessible :description, :name
  validates :name,presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  before_filter :find_todo_list,only: [:index,:new,:edit]
  before_filter :find_item,except: [:index,:new,:create]
  def index
    @items = @todo_list.items
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit

  end

  def show

  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
  def find_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end
  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  # GET /todo_lists
  # GET /todo_lists.json
  before_filter :find_todo_list ,except: [:index,:new,:create]

  def index
    @todo_lists = TodoList.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_lists }
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/new
  # GET /todo_lists/new.json
  def new
    @todo_list = TodoList.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/1/edit
  def edit

  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(params[:todo_list])
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render json: @todo_list, status: :created, location: @todo_list }
      else
        format.html { render action: "new" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_lists/1
  # PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update_attributes(params[:todo_list])
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end
 private
  def find_todo_list
    @todo_list = TodoList.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item || Item.new) do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :checked %><br />
      <%= f.check_box :checked %>
    </div>
    <div class="field" style="display:none;">
      <%= f.label :todo_list_id %><br />
      <%= f.number_field :todo_list_id, :value => todo.id %>
    </div>
    <div class="actions">
      <%= f.submit id: 'submit_form' %>
    </div>
<% end %>
<script type="text/javascript">
    //validate item name
    $(document).ready(function(){
        $('#submit_form').click(function(){
            if($.trim($('#item_name').val()).length == 0){
                alert("Item name can't be blank");
                return false;
            } else{
                return true;
            }
        });
    });
</script>

app/views/items/edit.html.erb
<%= render 'form',todo: @todo_list %>

app/views/items/index.html.erb
<h1>Listing items of <%= @todo_list.name %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Checked</th>
    <th>Todo list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.checked? ? 'yes' : 'no' %></td>
    <td><%= item.todo_list.name%></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_todo_list_item_path(@todo_list,item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', todo_list_new_item_path(@todo_list) %>

app/views/items/new.html.erb
<%= render 'form',todo: @todo_list %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Todo:</b>
  <%= @item.todo_list.name %>
</p>


<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Checked:</b>
  <%= @item.checked? ? 'Yes' : 'No' %>
</p>

<p>



<%= link_to 'Edit', edit_todo_list_item_path(@item.todo_list,@item) %> |
<%= link_to 'Back', todo_list_path(@item.todo_list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Assignment application</h1>
<%= yield %>

</body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Items Count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_lists.each do |todo_list| %>
  <tr>
    <td><%= todo_list.name %></td>
    <td><%= todo_list.description %></td>
    <td><%=link_to_unless(todo_list.items_count.eql?(0) ,todo_list.items_count,todo_list_items_path(todo_list)) %></td>
    <td><%= link_to 'Show', todo_list %></td>
    <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
    <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @todo_list.name %>
</p>

<p>
  <b>Description:</b>
  <%= @todo_list.description %>
</p>


<p>
  <b>Total Items:</b>
  <%=link_to_unless(@todo_list.items_count.eql?(0) ,@todo_list.items_count,todo_list_items_path(@todo_list)) %>
</p>

<p>


</p>

<strong>Create Item:</strong>
<%= render partial: "items/form", locals: {todo: @todo_list} %>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>